### ISSUE TITLE
calendar plugin choice

### ISSUE THREAD

**Issue by guandai** [like-minded-dk/group-web-shop#7]
try   WP FullCalendar    and  

[the event calendar](https://theeventscalendar.com/products/wordpress-events-calendar/?gad_source=1&gclid=Cj0KCQiAwbitBhDIARIsABfFYIIIvA9FXTzJX7Z5cL8II1IvEOUzDzXuzk9udBfcLBfaJyWxRxTm8_waAgJREALw_wcB)

**Comment by ningtandk** [comment]
I can see Calender function can be used by both products owners and selling partners, especially to set a valid period for the offer. I can imagine selling partner could potentially change and edit his offer time, making it different but within the valid time that set by product owners. 
e.g. product owner initiates an offer valid from 20th Jan to 20th Feb for his selling partners, a specific selling partner can adjust and make his offer to client from e.g. 25th Jan to 3rd Feb.

**Comment by guandai** [comment]
@ningtandk  this task is about to choose plugin . I will try some plugin to see which can fit us.   this task is not to develop the feature , but to choose a plug for later use

**Comment by ningtandk** [comment]
OK, got it.

**Comment by guandai** [comment]
there are many event calendar plugin

**Comment by guandai** [comment]
I found  “[The Event Calendar](https://theeventscalendar.com/products/wordpress-event-tickets/?utm_source=plugin-install&utm_medium=plugin-event-tickets&utm_campaign=in-app)” is useful  to work with wooCommerce .   we can give a try .   if has a pro license to support more feature.
but lets start with basic features for now. 

the plugin get this message :
```
Event Tickets does not support ticket sales via third party ecommerce plugins. If you want to sell tickets with WooCommerce, please purchase a license for [Event Tickets Plus](https://theeventscalendar.com/product/wordpress-event-tickets-plus/?utm_source=plugin-install&utm_medium=plugin-event-tickets&utm_campaign=in-app).
```

**Comment by guandai** [comment]
for this issue,   the conclusion is to try  :   The Event Calendar

**Comment by guandai** [comment]
we don't need to decide a event feature for now , so close this
