### ISSUE TITLE
Find Theme Plugin

### ISSUE THREAD

**Issue by guandai** [like-minded-dk/group-web-shop#77]
we need a dedicate theme for our site.

**Comment by guandai** [comment]
I found [WC Shop](https://wordpress.org/themes/wc-shop/)  is very nice,   it needs a theme builder  plugin  [WC booster ](https://www.eaglevisionit.com/downloads/wc-booster/)

**Comment by guandai** [comment]
Single Site License For Individual,   WC  booster cost    59$ / year

**Comment by guandai** [comment]
@guandai guandai theme should be here

**Comment by guandai** [comment]
we decide to use  Storefront as the basic theme,  as it is officially from WC  @ningtandk ,  I close this issue

**Comment by ningtandk** [comment]
Thanks Zheng, I will check it out later this week. But yes, please progress
as you see fits.
